name: '${project.name}'
version: '${project.version}'
description: '${project.description}'
main: 'it.mcdev.fine.core.Fine'
api-version: '1.13'
load: 'STARTUP'
author: 'MCDevITA'
website: '${project.url}'
